---
# tasks file for wordpress

################################[ Add repositories ] #######################################
- name: add-repository ondrej/apache2
  expect:
    command: sudo add-apt-repository ppa:ondrej/apache2
    responses:
      'Press \[ENTER\] to continue or Ctrl-c to cancel adding it.': ""
- name: add-repository ondrej/php
  expect:
    command: sudo add-apt-repository ppa:ondrej/php
    responses:
      'Press \[ENTER\] to continue or Ctrl-c to cancel adding it.': ""

- name: apt update
  command: apt-get update

#################################[ Install packages ] #######################################

- name: Install Webserver pkgs
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ web_pkgs }}"
  tags:
    - new_web
  notify:
    - restart apache2
    - FW_http

- name: Install php
  apt:
    name: "php7.4{{ item }}"
    state: present
  loop: "{{ php_items | flatten(1) }}"
  tags:
    - new_web


#######################################[ Setting wordpress ] ###################################
- name:  wget wordpress
  command: wget https://wordpress.org/latest.tar.gz

- name: unzip wordpress
  command: tar -zxvf latest.tar.gz -C /var/www/html/

- name: modify owner:group
  command: chown www-data:www-data /var/www/html/ -R

- name: modify document path
  replace:
    path: /etc/apache2/sites-available/000-default.conf
    regexp: '/var/www/html(.*)$'
    replace: '/var/www/html/wordpress'

- name: wordpress index template
  template:
    src: wp-config.j2
    dest: /var/www/html/wordpress/wp-config.php
    owner: www-data
    group: www-data
  notify:
    - restart apache2
  tags:
    - template
