- name: add-repository ondrej/apache2 
  expect:
    command: sudo add-apt-repository ppa:ondrej/apache2
    responses:
      'Press \[ENTER\] to continue or Ctrl-c to cancel adding it.': ""
- name: add-repository ondrej/php
  expect:
    command: sudo add-apt-repository ppa:ondrej/php
    responses:
      'Press \[ENTER\] to continue or Ctrl-c to cancel adding it.': ""
  
- name: apt update
  command: apt-get update
